AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  task-forge

  Sample SAM Template for task-forge

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  GetAllFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/lambda/get-all/
      Handler: get-all
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /
            Method: GET

  GetByIdFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/lambda/get-by-id/
      Handler: get-by-id
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET

  CreateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/lambda/create/
      Handler: create
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /
            Method: POST
